apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-py-helm.fullname" . }}
  labels:
    {{- include "app-py-helm.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "app-py-helm.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
