version: "3.7"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-size: 20M
    max-file: 10

networks:
  loki:

services:
  app_python:
    build: ../app_python
    ports:
      - 5000:5000
    networks:
      - loki
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 90M
    volumes:
      - ./data:/app/data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:5000 || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s


  app-kotlin:
    build: ../app_kotlin
    ports:
      - 8080:8080
    networks:
      - loki
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
      - ./data:/app/data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8080 || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  loki:
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging: *default-logging
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3100/ready || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 100M

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ls -l /proc/*/exe | grep /promtail
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s


  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - loki
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 200M
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 200M
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:9090/status || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

