name: Python CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt
      
      - name: Linter
        run: |
          pip install flake8
          flake8 --max-complexity=10 app_python

      - name: Tests
        run: |
          pip install pytest
          pytest app_pyton/test.py

  security:
    runs-on: ubuntu-latest

    needs: 
      - build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Snyk for vulnerabilities
        uses: snyk/actions/python-3.9@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    run-os: ubuntu-latest

    needs:
      - build
      - security
        services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app_python:latest ./app_python
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app_python:latest
